### ISSUE TITLE
Video on how to run this script (mac)?

### ISSUE THREAD

**Issue by martman0823-2** [BitcoinRaven/Bitcoin-Risk-Metric-V2#1]
Thank you for your hard work on this project!  Would you be able to publish a video or instructions on how to run this script on a mac?  I have tried pycharm and visual studio code with no success.  Thanks!

**Comment by BitcoinRaven** [comment]
you can [check google colab ](https://colab.research.google.com/drive/1DejFMbwO7S7Dd7aV4z7FuGBu9VtTOcSv?usp=sharing)which can be run with 0 coding skills, [or check this website](https://risk.bitstack.se/)
